title: "Akiode Emmanuel O"
# logo: /asset/img/headshot_circle.png
# description: text below image
show_downloads: true
theme: jekyll-theme-architect
email: "Akifem.emma@gmail.com"
mobile: "+2348169221496"
linkedin: "https://www.linkedin.com/public-profile/settings?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_self_edit_contact-info%3BTwJ68siFTQe0c5mozfExjA%3D%3D"


